// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/4/2024, 9:49:21 AM
const configMerger = require("/home/projects/sb1-ijqqwt/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/home/projects/sb1-ijqqwt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-ijqqwt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-ijqqwt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-ijqqwt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-ijqqwt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-ijqqwt/plugins/**/*.{js,ts,mjs}","/home/projects/sb1-ijqqwt/composables/**/*.{js,ts,mjs}","/home/projects/sb1-ijqqwt/utils/**/*.{js,ts,mjs}","/home/projects/sb1-ijqqwt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-ijqqwt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-ijqqwt/app.config.{js,ts,mjs}"] }));

module.exports = config
